productName = "pytauri-demo"
version = "0.1.0"
identifier = "com.pytauri-demo.app"

[build]
beforeDevCommand = "pnpm dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "pnpm build"
frontendDist = "./front/dist"

[app]
withGlobalTauri = true

[[app.windows]]
title = "pytauri-demo"
width = 800
height = 600

[app.security]
# csp =

[bundle]
active = false  # `pytauri` doesn't support bundling
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
