productName = "pytauri-demo"
version = "0.1.0"
identifier = "com.pytauri-demo.app"

[build]
beforeDevCommand = "pnpm -F=pytauri-demo dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "pytauri-bundler && pnpm -F=pytauri-demo build"
frontendDist = "./front/dist"

[app]
withGlobalTauri = true

[[app.windows]]
title = "pytauri-demo"
width = 800
height = 600

[app.security]
# csp =

[bundle]
active = false # `bundle` only supported on Windows for now
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
resources = ["python/"]
