[package]
name = "pyo3-utils"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }


[dependencies]
pyo3 = { workspace = true }
parking_lot = { workspace = true }
