[project]
name = "pytauri-plugin-notification"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["typing-extensions >= 4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
